### ISSUE TITLE
Correction for adoc-new-note  

### ISSUE THREAD

**Issue by Walckiers** [getreu/asciidoctor-notetaking#1]
I think that line 41 of adoc-new-note  should read
      `NewFileName="$Dir/$(date +%Y%m%d)-${Basename}.adoc"`
(Not
      `NewFileName="$Dir$(date +%Y%m%d)-${Basename}.adoc")`

See my posting 
`> Thanks to help off-list from a kind correspondent,`
`> I have the answers ... [1] `
https://groups.google.com/forum/#!topic/asciidoc/PS0vNkCUwYc

**Comment by getreu** [comment]
Yes, there should be a slash. Thank you! It is corrected in Version 1.7.
